<a href="https://colab.research.google.com/github/SuryARavichan/NATURAL-LANGUAGE-PROCESSOING/blob/main/NLP_PART_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
text = ['this is a line',
        'this is another line',
        'this is completely different line']
        

In [16]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [25]:
cv = CountVectorizer()


In [26]:
sparse_matrix = cv.fit_transform(text)

In [27]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 1, 1, 1]])

In [28]:
cv.vocabulary_

{'another': 0, 'completely': 1, 'different': 2, 'is': 3, 'line': 4, 'this': 5}

In [29]:
cv.vocabulary

In [30]:
cv.fixed_vocabulary_

False

In [31]:
tfidf = TfidfTransformer()

In [32]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [33]:
results = tfidf.fit_transform(sparse_matrix)

In [34]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.57735027, 0.57735027,
         0.57735027],
        [0.69903033, 0.        , 0.        , 0.41285857, 0.41285857,
         0.41285857],
        [0.        , 0.57292883, 0.57292883, 0.338381  , 0.338381  ,
         0.338381  ]])

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
tv = TfidfVectorizer()

In [38]:
tv_results = tv.fit_transform(text)

In [40]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.57735027, 0.57735027,
         0.57735027],
        [0.69903033, 0.        , 0.        , 0.41285857, 0.41285857,
         0.41285857],
        [0.        , 0.57292883, 0.57292883, 0.338381  , 0.338381  ,
         0.338381  ]])